export const PRODUCTION_LIST_REQUEST="PRODUCT_LIST_REQUEST";
export const PRODUCTION_LIST_SUCCESS="PRODUCT_LIST_SUCCESS";
export const PRODUCTION_LIST_FAIL="PRODUCT_LIST_FAIL";


export const PRODUCTION_DETAIL_REQUEST="PRODUCT_DETAIL_REQUEST";
export const PRODUCTION_DETAIL_SUCCESS="PRODUCT_DETAIL_SUCCESS";
export const PRODUCTION_DETAIL_FAIL="PRODUCT_DETAIL_FAIL";


export const PRODUCTION_CREATE_REVIEW_REQUEST="PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCTION_CREATE_REVIEW_SUCCESS="PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCTION_CREATE_REVIEW_FAIL="PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCTION_CREATE_REVIEW_RESET="PRODUCT_CREATE_REVIEW_RESET";